### ISSUE TITLE
Receive "We're sorry, but something went wrong." error when attempting to sign CLA

### ISSUE THREAD

**Issue by joelrbrandt** [clahub/clahub#104]
I'm attempting to sign JSHint's CLA here https://www.clahub.com/agreements/jshint/jshint

After I authenticate with GitHub, fill out the form, and click "submit", I get an error that says "We're sorry, but something went wrong."

This happens both in Chrome (40.0.2214.115 (64-bit)) and Safari (Version 8.0.3 (10600.3.18)) 

I'm filling the form with this information:

![screen shot 2015-02-26 at 6 34 23 am](https://cloud.githubusercontent.com/assets/908679/6393736/869b0cb6-bd81-11e4-880d-26c170845cd5.png)

**Comment by dionyziz** [comment]
I get an HTTP 500 error which I don't know if it's the same. Here's a screenshot of the error.

![screen shot 2015-02-27 at 1 18 20 am](https://cloud.githubusercontent.com/assets/544572/6404294/0b57a408-be1f-11e4-8054-b4483423d26e.png)

This occurs after the form is POSTed. The details I entered are:

Email: dionyziz@kamibu.com
Name: Dionysis Zindros
Country: Switerland
Type "I AGREE": I AGREE

**Comment by rwaldron** [comment]
Don't laugh—I can't sign the CLA for JSHint.

**Comment by mattflaschen** [comment]
I get the same error, in both Firefox and Chromium..

**Comment by schuyler1d** [comment]
I also get the same error (also need to sign CLA for JSHint).

**Comment by dionyziz** [comment]
I ended up signing via GPG.

**Comment by victor-homyakov** [comment]
FAIL. Can't sign the CLA.

**Comment by thefosk** [comment]
Same error.

**Comment by bollwyvl** [comment]
Me too.

**Comment by fabiomcosta** [comment]
I had the same issue

**Comment by svendahlstrand** [comment]
Same for me.

**Comment by jugglinmike** [comment]
Would anyone subscribed to this issue mind hopping back over to https://www.clahub.com/agreements/jshint/jshint and trying to sign again? @stevenbenner just successfully signed (thanks, Steven!), and I'm cautiously optimistic that this has magically fixed itself (especially since the webhook handler seems to be working as well)

**Comment by joelrbrandt** [comment]
@jugglinmike Works for me! Closing this issue.

**Comment by thefosk** [comment]
The bug is still there when I try to sign at https://www.clahub.com/agreements/Mashape/kong

**Comment by thefosk** [comment]
To give some more context, below is the snapshot of my form. I am also the creator of the CLA, so the issue may be related to owners signing their own CLAs.

https://www.clahub.com/agreements/Mashape/kong

![screen shot 2015-03-02 at 11 29 45 am](https://cloud.githubusercontent.com/assets/964813/6448547/9a31c4e4-c0cf-11e4-84fc-0e037e1e35d3.png)

**Comment by jugglinmike** [comment]
@thefosk I'm not so sure about that--I was the first to sign my project's CLA. Then again, @rwaldron is also an owner of the GitHub repository (but not the license on CLAHub), and he couldn't sign. It might be that he triggered the bug when he first attempted to sign.

@rwaldron: do you remember if you commented here immediately after attempting to sign?

**Comment by jasonm** [comment]
Hm, yes there are errors logged for these.  Here's a redacted subset for some of the JSHint-related ones: https://gist.github.com/jasonm/761b3d3d25aa697d3cda

Interestingly the `access_token` that I redacted from those logs doesn't appear attached to any CLAhub user; I'd expect it to be @jugglinmike 's token, i.e the owner of the Agreement.  @jugglinmike did you go through the OAuth flow anew recently?

If so, @thefosk have you gone through a new OAuth flow to get the reduced scopes for #101?  If not, could you try visiting https://clahub.com/sign_out and then signing in fresh, and see if that (1) sets the reduced GitHub OAuth scope, and (2) fixes this issue?

**Comment by jasonm** [comment]
If this is the case, then it is only the owner of the repo whose auth token needs to be updated, not every signer.

**Comment by jugglinmike** [comment]
@jasonm I can't say for sure :/ I did not create the CLA for JSHint until after gh-101 was deployed, but I already had an account with CLAHub. It sounds like this is related to my account and not necessarily tied to any specific license.

**Comment by thefosk** [comment]
@jasonm I confirm that after signing out, accepting the new OAuth scopes, and signing the CLA again it finally worked.

**Comment by Nijikokun** [comment]
New user registering on CLAHub I have this issue @jugglinmike I am not the owner.

Hundreds of people wanting to sign our CLA are having this issue.

**Comment by jugglinmike** [comment]
@Nijikokun You might try de-authorizing CLAHub from the GitHub administrative interface, then completely signing out of both CLAHub and GitHub and then signing in again. The owner of the CLA should try the same (in that case, de-authorizing may delete the existing CLA--you should confirm with the maintainers before trying that if you already have signatures). This may or may not have been what fixed the issue for me.

That's about as much assistance as I can provide. If things still don't work for you, then @jasonm is probably your best bet--he is the maintainer of CLAHub ( and a swell guy :) )

**Comment by Nijikokun** [comment]
I've opted to forgo further usage of clahub in favor of google forms this
was breaking user trust.
