### ISSUE TITLE
Receive "We're sorry, but something went wrong" error when delivering web hook

### ISSUE THREAD

**Issue by jugglinmike** [clahub/clahub#105]
GitHub has received a 500 error when delivering web hooks for [the jshint/jshint project](https://github.com/jshint/jshint) consistently since 2015-02-25 11:22:44 . This may be related to gh-104, but since the error is a generic 500 and being reported by a separate resource, it's hard to say.

![screenshot from 2015-02-26 19 37 39](https://cloud.githubusercontent.com/assets/677252/6405300/aca4b79a-bdef-11e4-8198-5fddf12b25a9.png)

I'm happy to share request/response pairs as necessary.

**Comment by mzagaja** [comment]
Is this still an active issue? I checked the logs and JSHint seems to be working in there and the latest Pull Request looks like it successfully checked the CLA.

**Comment by tamird** [comment]
https://github.com/cockroachdb/cockroach is still affected as of this writing.

**Comment by mzagaja** [comment]
Hi @tamird please try the following steps (or have whomever setup cockroach do so):

1. Go to https://github.com/settings/applications
2. Revoke access to clahub
3. Go to http://www.clahub.com/ and click "sign out" if you are already signed in.
4. Go to http://www.clahub.com/ and sign in to clahub 
5. Grant it the appropriate GitHub permissions
6. Try submitting a new pull request to see if it works.

**Comment by tamird** [comment]
Turns out we're not actually using clahub anymore, and simply neglected to delete the webhook. Consider my comment moot.

**Comment by mzagaja** [comment]
No worries. From my end it looked like there were not appropriate permissions so someone must have started the removal process but did not finish.

**Comment by tamird** [comment]
Sounds about right. Might be worth improving the returned error for the
future.
