### ISSUE TITLE
Takes a long time for checking if CLA is signed

### ISSUE THREAD

**Issue by kermie** [clahub/clahub#108]
Sometimes it takes up to five days to check if a user signed the CLA. Have no clue what's going wrong or in which queue these requests stuck. Obviously (as it appears after a couple of days) we didn't do anything wrong with the implementation.
Cheers!

**Comment by mzagaja** [comment]
Hi @kermie is this still an active issue? After becoming familiar with the code base I don't see any obvious reasons there would be a delay in POSTing. The code base does not use any task runners (sidekiq, etc. though maybe a good idea in the future) so it should either update GitHub or fail (though maybe GitHub re-fires the web hook if it fails?).

**Comment by kermie** [comment]
Thanks for your reply @mzagaja . In the mean time we had to switch to another system for checking the CLAs, so I can't answer your question whether the effect still appears or not. Thanks anyway!

**Comment by mzagaja** [comment]
No problem, just want to make sure.
