### ISSUE TITLE
Contributors getting "We're sorry, but something went wrong." on my agreement

### ISSUE THREAD

**Issue by lminiero** [clahub/clahub#109]
Not sure what may be wrong. I created the agreement yesterday and it seemed to work fine for a while, but since a few hours ago it seems to have stopped working, as three different users reported they got a "We're sorry, but something went wrong." error. Trying to sign out and retry apparently didn't solve the issue.

Any additional info I can provide to sort this out? The link to my CLA is https://www.clahub.com/agreements/meetecho/janus-gateway

Thanks!

**Comment by lminiero** [comment]
Problably related to #105 as I just tried myself and I saw a 500 error being returned.

**Comment by rnicholus** [comment]
same issue on our end

**Comment by lminiero** [comment]
@rnicholus I eventually gave up and reimplemented something similar myself. I don't think the project is maintained anymore as I tried contacting the author on twitter and didn't get a response there either. Unfortunately it looks like you also get a 500 error when destroying the agreement, which means you need to manually remove the pull request webhooks clahub created.

**Comment by rnicholus** [comment]
@lminiero Yes, I figured this project was may be dead. Thanks for the confirmation and the info. I'll proceed to remove from my repo as well.

**Comment by SirCmpwn** [comment]
@lminiero have you made your solution public?

**Comment by lminiero** [comment]
@SirCmpwn no but it's really much simpler in concept. No github webhooks implemented for pull requests for instance. I just make use of the github authentication process to "sign" an HTML form that asks for the same things clahub does, so something quite crude that should be quite easy to replicate.

**Comment by Marak** [comment]
I have the same problem here. Using this for http://hook.io

The project is dead? :-(

@jasonm ?

**Comment by Marak** [comment]
Does anyone want to put up a new version of this somewhere?

**Comment by mzagaja** [comment]
Going to close this as stale since I do not have logs from 2015 to do any diagnostics and I do not see any recent log entries from these projects there. If this issue re-appears please feel free to open a new issue.
