### ISSUE TITLE
Incorrectly says someone signed

### ISSUE THREAD

**Issue by kellyelton** [clahub/clahub#110]
I suppose the best way to show you what's going on is to show you what I'm seeing

The pull request https://github.com/octgn/OCTGN/pull/1433

and then the CLA https://www.clahub.com/agreements/octgn/OCTGN

So that user has never signed the CLA, and it says that he did.

**Comment by mzagaja** [comment]
Production says the user signed the agreement on 5/19/2015 so I'm going to close this since this is no longer a usable test case that I can investigate. If it happens again please feel free to open a new bug with a live test case like you did with this one.
