### ISSUE TITLE
Github Permissions / Why were Github OAuth access roles changed?

### ISSUE THREAD

**Issue by Marak** [clahub/clahub#115]
Tried to log into the app today and was greeted with an updated Github access settings.

The app is now requesting a bunch of new permissions. Are these new permissions actually necessary? 

<img src="http://i.imgur.com/ZZkiqec.png"/>

**Comment by Marak** [comment]
Still the same issue.

Cannot use the service anymore with these new invasive oauth roles.

:-1:

**Comment by mzagaja** [comment]
Hi @Marak,

I looked into this and it appears that this was a result of #101 which actually made the permissions CLAhub requested less permissive than the previous iteration. If you think there are permissions that CLAHub doesn't need after reviewing that pull request let me know what you think the scope should be, and also feel free to submit your own pull request if you can get them working on your own instance.

**Comment by mzagaja** [comment]
Closing this since I we haven't received further feedback. Happy to continue the discussion if you wish to re-open this in the future.
