### ISSUE TITLE
Can't delete or create a new CLA

### ISSUE THREAD

**Issue by rnicholus** [clahub/clahub#121]
I went to create a CLA, and realized that I already have one (probably from a couple years back). However, it doesn't appear to be working. So, I attempted to delete the CLA in order to re-create, but that failed with an error. Repo is FineUploader/fine-uploader. Can you clear my account so I can start over?

**Comment by mzagaja** [comment]
Can you clarify what you mean by not working? Maybe paste a copy of the error message? If possible I'd prefer to fix the bug so it works for everyone going forward. However I can delete the agreement if you'd like, but please note this will be a destructive operation so I'd recommend an export of a copy of signees somewhere first.

**Comment by rnicholus** [comment]
I am under the assumption that clahub will tag new PRs depending on the CLA status of the committer. That isn't currently happening. If this can be fixed without deleting/re-creating my CLA, that would be great.

**Comment by mzagaja** [comment]
Yeah I don't see any hooks on your end:

```
curl -i https://api.github.com/repos/FineUploader/fine-uploader/hooks                                                                      
HTTP/1.1 404 Not Found
Server: GitHub.com
Date: Tue, 03 May 2016 20:35:34 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 87
Status: 404 Not Found
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 52
X-RateLimit-Reset: 1462310645
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 8CF7DA4B:76D5:29E7E5B7:57290B96

{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```
Since it's an issue with the hook I do think it'll have to be recreated so I'll delete it for you.

**Comment by mzagaja** [comment]
Actually going to slate this for tomorrow as I need to make sure I appropriately backup database state and have it ready for rollback before I go ahead and do that edit. I'll comment again when it is set.

**Comment by rnicholus** [comment]
Thanks for the quick response and for donating your time to this project.

**Comment by mzagaja** [comment]
Ok I deleted the agreement itself but left the orphaned signatures in the DB. Given that signatures link to an agreement_id and user_id I don't believe this should cause any issues, but you might want to have someone test signing it. I also may be able to manually update the signatures from the old agreement id to the new one after you create the new agreement if you'd like to test doing that as well.

**Comment by rnicholus** [comment]
Seems to work. Thanks! If you _could_ update this new CLA for FineUploader/fine-uploader with the old signatures, that would be great!

**Comment by mzagaja** [comment]
I'm forced to confess here that I didn't actually run a SELECT in the DB to see if there were old signatures when I made that previous offer and merely presumed that they weren't deleted since I was manipulating the DB directly and not touching that table. However it appears that the database had been cleared of those signatures, my guess, based on the app code, is this occurred when you attempted the initial delete. So people will have to start from scratch. Sorry about that, but hope things work well going forward.

**Comment by rnicholus** [comment]
No problem. Thanks for your help!
