### ISSUE TITLE
Feature Request: Accept commits committed by GitHub.com

### ISSUE THREAD

**Issue by jugglinmike** [clahub/clahub#135]
When GitHub.com users author commits through the GitHub interface, the
resultant commit lists their identity as the commit author, but it lists the
committer as `GitHub <noreply@github.com>`. This interferes with the CLA
verification process because that e-mail address will not appear in any
signature databases.

Since the basic behavior is semantically accurate and definitely intentional,
it seems unlikely to change (more on this in a moment). Therefore, in order to
allow CLAHub users to accept contributions authored through the GitHub.com
interface, this project should be updated to account for this detail.

I can think of two solutions:

- Unilaterally whitelist "noreply@github.com" for all CLAHub accounts.
- Allow CLAHub users to insert this address themselves

The first is implicit, which is both a positive and negative aspect. It means
users have less to configure, but it also means they may not fully understand
how CLAHub is behaving. And while GitHub is unlikely to stop authoring commits
on behalf of their users, it seems possible that they would change the
"noreply@github.com" e-mail address, which would require another fix from
CLAHub.

The second solution requires more of the user, but this means less room for
surprises. As it happens, there is already an open issue for this basic
functionality (although it does not mention the use case described above)--see
https://github.com/clahub/clahub/issues/112

(For reference, this came up in the context of a contribution to the JSHint
project: https://github.com/jshint/jshint/pull/2953)

**Comment by mzagaja** [comment]
Oh, I think/wonder if this might be the same issue we're facing in #133 that I haven't pinned down yet. A potential third path forward might be to constrain CLAHub to looking at the author as opposed to the committer.

**Comment by mzagaja** [comment]
We have decided the path forward is to whitelist the GitHub.com contributor (though the author will still have to have signed the CLA for the status to be "green"). I am going to code a fix to be deployed.
