### ISSUE TITLE
[Question] Proof of CLA

### ISSUE THREAD

**Issue by elbenfreund** [clahub/clahub#137]
hello community,

please excuse if this is the wrong place to raise the issue, but I was wondering what sort of actual proof ``clahub`` to be presented in front a court of law if it ever comes down to it. Is there any actual signing procedure and/or a way to extract a signed pdf?

Thank you for your effort and contributions: Eric.

**Comment by elbenfreund** [comment]
Is there any news on this? If this is the wrong place to ask, please let me know :)
Going through the effort of setting up a solid CLA policy seems a bit questionable if the only "evidence" that a user signed is the csv one can export.

**Comment by mzagaja** [comment]
Hi @elbenfreund my suggestion would be that if you are worried about whether these records will be admitted in a court of law in your jurisdiction is to speak with your own counsel who will have specific knowledge of the rules of evidence in your jurisdiction and then feed any needs back to us in the form of a pull request with whatever the relevant feature is built out. On our end we are looking at options going forward of providing additional documentation in the form of e-mail receipts. Besides that we also have the website itself with the list of signers. We also have research going into what other measures if any we should take on our end and that will certainly influence development decisions going forward from our side, but we cannot be your lawyer. I hope that helps!

**Comment by elbenfreund** [comment]
Thank you for your reply, it is much appreciated. I want to stress that I am well aware that you "can not be my lawyer", and didn't expect you to. My question does neither refer to a particular jurisdiction or court setup but was of general nature. I wish to apologize if I gave the impression that I would seek legal counsel.

 Clearly CLAs are a tool to avoid and ultimately, if need be, settle (legal) disputes. To that end you (the clahub community) must have a workflow in mind of how in general and broad terms this is achieved by the (lovely) service you provide. From my current insight I am simply not sure I understand what this workflow would be. Clearly it can not be, "lets have an elaborated process to generate CSVs/random websites that claim people have "signed something".

I do understand this is not an easy question as it ultimately relates to the question on how to provide a solid, transparent, validateable and automated signing process that would be usefull in *any* legal framework.

Please feel free to cut off this discussion if you feel it is not usuful to the project, I do not intend to waste your time but to improve the status quo.
One way or the other, thank you again for your time and contributions.

**Comment by mzagaja** [comment]
Hi @elbenfreund, since we only took over this project recently I can't speak for the folks that worked on it before we started maintaining, but we are going to have our experts look into this issue over the next few weeks and then plan to provide resources about enforceability of online agreements that can help answer your questions. As far as the functionality goes, right now what you see is what you get which is the CSV and the website. Once we hear back from the researchers, their input may shape other functionality we add in the future. Stay tuned.

**Comment by elbenfreund** [comment]
Thank you very much for this most helpful answer. This indeed provides the solid feedback about 'what is there right now' and your general direction. I look forward to your experts findings and the resulting resources. Is there any particular communication channel that I should keep an eye on with regards to this?

Thanks again for your continuous work and maintaining the project.
Eric

**Comment by mzagaja** [comment]
I will make sure to post an update to this thread and will probably add a page to the main CLAHub website. I checked in with the folks at the Cyberlaw Clinic earlier this week and they're still working on it. They're a fantastic resource and enthusiastic about this project, but also highly in demand.

**Comment by elbenfreund** [comment]
Hi @mzagaja 
Is there by any chance news on this? I brought up questions similar to the ones raised here with the FSFE recently and reference this issue so while it is closed I wondered if you were able to get any feedback so far?

**Comment by silverhook** [comment]
@elbenfreund I’m a member of the FSFE Legal Team (and was its coordinator for several years), but haven’t seen that question pop up on the relevant mailing lists. Can you point me to it?

I have been giving this question some serious though lately …

**Comment by elbenfreund** [comment]
As I in all honesty did not anticipate the lack of a clear go-to-procedure and felt it must be me being thick. So I took the opportunity and raised the issue at the FSFE booth at 33c3 (talking to "Silvian", who tried to be very helpful!). In a follow up email I got from him he told me that "Hannes" suggested "clahub"... at which point we went full circle :D

**Comment by silverhook** [comment]
Hehe, so it seems ;)

As soon as the FLA 2.0 gets published (the legal text is finally done), I hope to find more time to think about it more. But it seems to me that there might be a simple technical solution for legally valid signing. How you want to present that to the courts, is another matter.

**Comment by mzagaja** [comment]
Hi @elbenfreund, apologies for the lack of updates or announcement, but I wrapped up my fellowship at Berkman Klein and am no longer the maintainer for CLAHub. I had not heard any updates from the Cyberlaw Clinic when I was there, but maybe @ryanttb or someone else at Berkman can check-in.

**Comment by ryanttb** [comment]
Sadly, I haven't heard anything new. I'll ping the Clinic as I am not able to answer any questions of law myself.

**Comment by mitar** [comment]
Should this issue be reopened for now then?

**Comment by mitar** [comment]
I think what constitutes a valid signature online probably depends on country to country.

Just recently I had to sign something using https://www.docusign.com/. We might want to check how they are doing it. But from my feeling it was more or less "type your name here, draw something here, and press submit and we will store it into the database and give you a PDF where your name (and others who have to signed) is marked as signed".

**Comment by elbenfreund** [comment]
Thank you @mzagaja and @ryanttb for your fast replies. What @mzagaja departure mean for CLAhub as a whole? Is @ryanttb taking over as a proper maintainer? Clearly there is documented interest as well as need and its topic seems to be a perfect fit for the Berkman Center so I would be most grateful if it could continue to grow under its guidance.

**Comment by silverhook** [comment]
> I think what constitutes a valid signature online probably depends on country to country.

Yup. There’s a really good [research paper][rens] on this already on what formalities are needed for a CAA or CLA to be valid in several jurisdictions. In almost all reviewed jurisdiction it turns out a digital signature is enough.

[rens]: https://script-ed.org/wp-content/uploads/2013/08/rens.pdf

**Comment by elbenfreund** [comment]
@mitar @silverhook I think at its root there are two separate questions to be dealt with if CLAs are to provide any real reassurance.
1. A documented "signing process for the CLA "that can ensure that the CLA has been signed by a particular natural person / online account.
2. A way to document the (internal) signing process or to produce some kind of verifiable information to the actual CLAhub user that proofs the claim.

I think (1) may easier than (2). The problem is that this is a transaction between the signing party and CLAhub. At this point the best case is that CLAhub can be sure the signing worked as expected.

(2) Is what will matter at the end. I understand that the details of what kind of "proof" will be effective in front of a court depends on the juristiction and that CLAhub can not account for all of them. But it seems clear that there needs to be some means by which CLAhub users can get some token/document/... that is somewhat usable to make the point "X signed Y" without having insight into the CLAhub signing process itself.

**Comment by silverhook** [comment]
@elbenfreund I agree with your analysis that these are two distinct problems, but re problem (1) for a _valid_ copyright assignment or exclusive license, you still have to fulfil the formality requirements of the jurisdiction that specific agreement between those two parties. And I think both (1) and (2) could be potentially solved with some more research and creative lawyering around what is deemed a valid digital signature.

**Comment by mitar** [comment]
> In almost all reviewed jurisdiction it turns out a digital signature is enough.

But what exactly constitutes a digital signature? A click on the form? A click on the form served by HTTPS? A personal certificate used to sign a document? A FIDO U2F token signing a document? An SGX enclave running on the server signing that the user really clicked the form button?

**Comment by mitar** [comment]
BTW, I do not think we should solve this more than any other enterprise here. There are clear issues here inside the wider ecosystem of digital signatures and enforcement of them, but I am not sure if we can really fix those issues ourselves. What we can probably do is do an industry-standard. Whatever that is.

**Comment by silverhook** [comment]
> But what exactly constitutes a digital signature?

Many things, starting with a government CA-issued certs and PGP keys.

I’d argue that an SSH key used to commit to a git repo should qualify as well. And wrapping a CLA around that (through a DCO-like system) should be doable IMO.
