### ISSUE TITLE
Renamed Repository

### ISSUE THREAD

**Issue by henrikekblad** [clahub/clahub#140]
Hi, 

We renamed a repository and wonder if there is something we need to do to make the CLAhub to continue work (with the previous list of signed contributors)?

https://github.com/mysensors/Arduino -> https://github.com/mysensors/MySensors

**Comment by mzagaja** [comment]
I updated the repo_name in the database manually as a temporary fix. You may have to re-trigger the repohooks for it to work. If you try a new pull request and it is still broken let me know and I'll investigate further.

**Comment by henrikekblad** [comment]
I've re-triggered hook but we get a 500 error response. 

Anything I can provide to help you debug the issue?

**Comment by mzagaja** [comment]
Hi @henrikekblad it looks like your auth token doesn't have the appropriate scopes. Try deleting and re-adding CLAHub as an authorized application and then re-send the repo hook (see https://github.com/clahub/clahub/issues/134#issuecomment-232142043). Also please remember to update your CONTRIBUTING.md to point to the updated agreement for the users.

**Comment by henrikekblad** [comment]
Delete + re-adding did the trick. Thanks for all the help @mzagaja!
