### ISSUE TITLE
CLAHub passes despite one of commits is authored by a person who has not signed CLA

### ISSUE THREAD

**Issue by mitar** [clahub/clahub#141]
I just added CLAHub to [my project](https://github.com/peer/mind) and I see that it passed on the pull request where there is also a person who has not signed a CLA:

![screen shot 2016-08-08 at 1 19 49 am](https://cloud.githubusercontent.com/assets/585279/17473618/3dc98cb2-5d06-11e6-865b-f0087457402a.png)

![screen shot 2016-08-08 at 1 20 18 am](https://cloud.githubusercontent.com/assets/585279/17473620/4cf4e826-5d06-11e6-82a6-32b5ce6183fa.png)

But chilldude has not yet signed the CLA.

What is happening?

**Comment by mitar** [comment]
What is this. CLAHub just now switched to red. Without me doing anything.

![screen shot 2016-08-08 at 1 22 09 am](https://cloud.githubusercontent.com/assets/585279/17473718/d393d0a4-5d06-11e6-94ab-ce6bb71126f6.png)

**Comment by mitar** [comment]
Oh, somebody else signed CLA in this moment, triggering rechecking here or what?

But this still means that this pull requests looked OK for some time, despite not being OK?

**Comment by mzagaja** [comment]
This is weird to me because the logs indicate that CLAHub saw it as failing:

```
Aug 07 23:23:47 clahub app/web.2:  Started GET "/agreements/peer/mind" for 199.27.128.235 at 2016-08-08 06:23:46 +0000 
Aug 07 23:23:47 clahub heroku/router:  at=info method=GET path="/agreements/peer/mind" host=www.clahub.com request_id=a22dbc21-6222-4def-a350-c14e8c175c2d fwd="64.62.133.42,199.27.128.235" dyno=web.2 connect=0ms service=45ms status=200 bytes=19327 
Aug 07 23:24:17 clahub app/web.1:  Started POST "/agreements/peer/mind/signatures" for 199.27.128.235 at 2016-08-08 06:24:16 +0000 
Aug 07 23:24:17 clahub app/web.1:  PushStatusChecker#check_and_update for push peer/mind:4f458970f2eaec74fdd1cf2f4bed9e48da35d6d3,5b025efa994ac9bb21498a226cae8010554a8035,af86346650932e443edb31516d2009e43002548a,c3ccf7a0dba87ab320dfb763908995395a9bb5b6 
Aug 07 23:24:17 clahub app/web.1:  check_commit for 4f458970f2eaec74fdd1cf2f4bed9e48da35d6d3: nil: false 
```
I don't have sufficient logging detail to be able to know what it sent outbound at the moment. Once I'm able to push an update to get that detail I will try and see if we can reproduce this.

**Comment by mitar** [comment]
There should be two pushes, are there two?

Maybe if there is no push, for a new pull request, it defaults to green? So that pull request already existed with all those commits when I started adding CLAHub. I added CLAHub and then I went to the pull request and it was green. Then it seems one other contributor signed the CLA (for another pull request) and it rerun this pull request as well? Is this how it happens?

**Comment by mzagaja** [comment]
There was a push that succeeded after that according to the logs:
```
Aug 07 23:51:34 clahub heroku/router:  at=info method=POST path="/repo_hook" host=www.clahub.com request_id=9b3bc810-1d0a-4a13-adcc-83d15142bead fwd="192.30.252.46,173.245.52.228" dyno=web.2 connect=0ms service=100ms status=200 bytes=587 
Aug 07 23:51:34 clahub app/web.2:  PushStatusChecker#check_and_update for push peer/mind:07c1551e72a3333ce5b4b6e097e6183ef3623d6d 
Aug 07 23:51:34 clahub app/web.2:  check_commit for 07c1551e72a3333ce5b4b6e097e6183ef3623d6d: 4646 mitar.github@tnode.com: true 
Aug 07 23:51:34 clahub app/web.2:  check_commit for 07c1551e72a3333ce5b4b6e097e6183ef3623d6d: 4646 mitar.github@tnode.com: true 
Aug 07 23:54:05 clahub app/web.1:  Started POST "/repo_hook" for 173.245.52.78 at 2016-08-08 06:54:04 +0000 
Aug 07 23:54:05 clahub app/web.1:  "push" 
```

I actually have a whole bunch logged:

```
Aug 07 23:24:17 clahub app/web.1:  PushStatusChecker#check_and_update for push peer/mind:4f458970f2eaec74fdd1cf2f4bed9e48da35d6d3,5b025efa994ac9bb21498a226cae8010554a8035,af86346650932e443edb31516d2009e43002548a,c3ccf7a0dba87ab320dfb763908995395a9bb5b6 
Aug 07 23:24:18 clahub app/web.1:  PushStatusChecker#check_and_update for push peer/mind:3c6f8dcdc06faa378bae0cec8d52be9748c7a8d1 
Aug 07 23:51:34 clahub app/web.2:  PushStatusChecker#check_and_update for push peer/mind:07c1551e72a3333ce5b4b6e097e6183ef3623d6d 
Aug 08 00:54:42 clahub app/web.2:  PushStatusChecker#check_and_update for push peer/mind:5daff563b3ee0d79c43f82f111ccc07bc5ff1751,18df98e3b165df866c7a85359993e669c5b017d8 
Aug 08 00:57:21 clahub app/web.2:  PushStatusChecker#check_and_update for push peer/mind:8cf5333f73d8f8a9eb875e693e4a12247200bec5 
Aug 08 01:08:39 clahub app/web.1:  PushStatusChecker#check_and_update for push peer/mind:4f458970f2eaec74fdd1cf2f4bed9e48da35d6d3,5b025efa994ac9bb21498a226cae8010554a8035,af86346650932e443edb31516d2009e43002548a,c3ccf7a0dba87ab320dfb763908995395a9bb5b6,be41c4a4c37f1c3590b1fb1c091097fa55d70b3e 
Aug 08 01:08:39 clahub app/web.1:  PushStatusChecker#check_and_update for push peer/mind:e9daa9444fd3ecfdf9481f99f368aa1bfd56b6b0,ffc147df343f50898fcfe63f1076f90c78731b10,96c7f326d2c291b7e6469d20cfd78043b467a494,85f3399351df0385028785bb8589c5bde6af60cc,ee3e782a54badfb71c611909ca78f93d7794addc,eb9ce68a5e78e7d6df088878574e1b55a69aedef,6a914f50104fe36a82dc75bce1165746ca0ca30f,1041b0a11d761f7f46871f69d13fdc5b959b6335,f2260a08e6e2c15021146b6d0e0d2ed446ea3990,e139fc2b15f414f959f4c4e8f4a69f9017fee213,30a623ce641678ad9b31b3cd22c6cc68ff1a0c0a,87d168ab3da45d8983eba2c3809133f6f9f984c4,32de81a431d67c19e8b6ba7ac28a86a7510622c1,c61b5c00594cc9a93f596a1b2e6f8700af8dbd30,9f7e2a4fcd1f9ee335219dc654dd44d363355cfc,07c1551e72a3333ce5b4b6e097e6183ef3623d6d,5daff563b3ee0d79c43f82f111ccc07bc5ff1751,18df98e3b165df866c7a85359993e669c5b017d8,8cf5333f73d8f8a9eb875e693e4a12247200bec5,be41c4a4c37f1c3590b1fb1c091097fa55d70b3e 
Aug 08 01:21:38 clahub app/web.1:  PushStatusChecker#check_and_update for push peer/mind:4f458970f2eaec74fdd1cf2f4bed9e48da35d6d3,5b025efa994ac9bb21498a226cae8010554a8035,af86346650932e443edb31516d2009e43002548a,c3ccf7a0dba87ab320dfb763908995395a9bb5b6,be41c4a4c37f1c3590b1fb1c091097fa55d70b3e 
Aug 08 01:21:38 clahub app/web.1:  PushStatusChecker#check_and_update for push peer/mind:3c6f8dcdc06faa378bae0cec8d52be9748c7a8d1 
Aug 08 01:25:35 clahub app/web.2:  PushStatusChecker#check_and_update for push peer/mind:3c6f8dcdc06faa378bae0cec8d52be9748c7a8d1,b518d901506e8902763e11a24e7baac0f2ce6e0f 
Aug 08 01:25:35 clahub app/web.1:  PushStatusChecker#check_and_update for push peer/mind:3c6f8dcdc06faa378bae0cec8d52be9748c7a8d1 
Aug 08 01:39:04 clahub app/web.1:  PushStatusChecker#check_and_update for push peer/mind:3245f53dbb05c712de3a31208cff1bb131a84b68 
Aug 08 01:46:00 clahub app/web.1:  PushStatusChecker#check_and_update for push peer/mind:ed8879b134a9a9263f4406f4316d078abc5015d3
```
I have logging that tells me if CLAHub thinks it succeeded or failed on each one if you want me to dig into any specific one of these, along with the payload from the web hook, but just not logging on what the outbound POST request was.

**Comment by mitar** [comment]
So I care about checks which include [this commit](https://github.com/peer/mind/pull/131/commits/4f458970f2eaec74fdd1cf2f4bed9e48da35d6d3). They should all fail. Do your logging tells that any succeeded?

Anyway, strange. :-) If I can be of some help, tell me. I will try to see if it happens again.

**Comment by mzagaja** [comment]
I finally got the deploys working again (there was a Heroku upgrade I had to make some changes for). My logging for the commit you linked to all says that they failed on CLAHubs end which is apparently a mismatch between what the logs say and what might have been POSTed to status, so I think the next step on my end is to try and log and debug the outbound POST request. I will try and deploy an update Monday that can help with that and ask about trying to reproduce next week.

**Comment by mzagaja** [comment]
Ok after looking at things I'm not sure there is additional logging I can use to debug this, as the logging that is present should print whether the commit passed or failed before it POSTs that status to GitHub. I was unable to reproduce this in another repo. If you can reproduce this with another repo or pull request let me know. Otherwise I am content to blame it on a fluke from GitHub for now.

**Comment by mitar** [comment]
OK. I also think it was some type of a fluke. I think we should close this for now and if somebody else will have another example later on they can comment here and we could reopen.
