### ISSUE TITLE
Webhook calls from GitHub are failing

### ISSUE THREAD

**Issue by mitar** [clahub/clahub#144]
I see in GitHub logs that webhooks which GitHub has been making towards clahub has been failing with 500 error since August 19.

**Comment by mzagaja** [comment]
Taking advantage of our new logging I deployed I can see you were issued an updated OAuth token on August 20th at 01:18 UTC after which CLAHub's POSTs to GitHub for peer/mind started failing. I also have just tested and confirmed that anytime you login to GitHub from CLAHub you will be issued a new OAuth token. The issue arises under the following reproducible scenario:

1. Sign-in to GitHub and setup a CLA for a repo
--> Logs indicate GH issues an OAuth token with appropriate scopes
2. Sign out of CLAHub
3. Go to any other arbitrary repo that uses CLAHub and follow the link to their CLA from their CONTRIBUTING.md
4. Click the sign-in link from the signature 
---> Logs indicate GH issues an OAuth token and manual testing reveals it has no_scope

From this point forward all the maintainers CLAs will not update properly and receive 500 errors. The easy fix is to go to http://www.clahub.com/ and sign in. You may need to sign out first. From this page GitHub will issue you a working token and all your pull requests will work again.

I have begun research into figuring out what the best practice is for multiple scopes within the same application with OmniAuth as it is clear to me now that the omniauth-github gem and/or omniauth itself, or at least the current implementation of this did not anticipate this scenario. I am not completely sure how/why the OmniAuth-GitHub gem keeps asking for new OAuth tokens given that [the GitHub OAuth tokens do not expire](https://gist.github.com/technoweenie/419219#gistcomment-3232). Hoping to try and figure out a fix for this edge case and deploy that fix later in the week. I am open to pull requests and suggestions/advice in the mean time.

Also going to note this is the same issue as #134.

**Comment by mitar** [comment]
Oh, this is amazing research! It seems really so.
