### ISSUE TITLE
Allow optional dummy signatories

### ISSUE THREAD

**Issue by elbenfreund** [clahub/clahub#147]
If one uses clahub as a PR requirement automated bots (for example as provided by requires.io) that auto generate commits/PRs will taint the commit.
Would it be feasible to "whitelist" certain github username so that they appear as if they signed the CLA?

**Comment by mzagaja** [comment]
Also requested in #146. This is "in the pipeline" but not in my near term docket. However I'm open to reviewing and accepting a pull request if anyone wants to tackle this issue.

**Comment by elbenfreund** [comment]
Thank you for your feedback. Will close this one in favor of #146 then.
