### ISSUE TITLE
Update account shown when signing into GitHub

### ISSUE THREAD

**Issue by kreynen** [clahub/clahub#159]
![screen shot 2017-03-30 at 4 31 52 pm](https://cloud.githubusercontent.com/assets/385234/24720231/93729162-19f9-11e7-80b9-8904f8c7bddf.png)

I'm not sure if something changed in GitHub's UI, but users now see @jasonm's profile picture when authorizing this app.  Nothing against Jason, but this doesn't really "trust me".  It would be much better if the account was linked to an organizational account related to https://github.com/berkmancenter

**Comment by jasonm** [comment]
Agreed! I've updated the logo on this OAuth Application (CLAHub Signatures) to reflect the CLAHub visual identity.

**Comment by jasonm** [comment]
<img width="348" alt="sign_in_to_github_ _github" src="https://user-images.githubusercontent.com/1031/28146241-2fd0b266-672d-11e7-9f9b-ab85418e336e.png">
