### ISSUE TITLE
OAuth scope and rights too permissive?

### ISSUE THREAD

**Issue by jasonm** [clahub/clahub#17]
We don't need read+write for private repos, and this is rightfully concerning to users:

UPDATE: We sure don't need `repo`, but it'd be nice to narrow `public_repo` to `public_repo:status`.

http://developer.github.com/v3/oauth/#scopes

**Comment by ferventcoder** [comment]
Can this be closed? https://github.com/clahub/clahub/pull/101#issuecomment-75479008

**Comment by genevec** [comment]
Yup. Closing! See #101.
