### ISSUE TITLE
Delete/Modify the CLA of a project.

### ISSUE THREAD

**Issue by gdfm** [clahub/clahub#53]
Hi,

I would like to redo the CLA for one of my projects (gdfm/samoa). Is there a simple way to delete the CLA and create a new one?

**Comment by LukePulverenti** [comment]
Same issue here. can I send you our new cla so that it can be updated? thanks.

**Comment by jcarsique** [comment]
Hi,
Could you please delete the CLA on https://github.com/nuxeo-sandbox/nuxeo-pullrequest ? 
I want to register a different text with another user.
Thanks
