### ISSUE TITLE
Only ask for public read-only OAuth scope for signers

### ISSUE THREAD

**Issue by jasonm** [clahub/clahub#54]
We only need the `public_repo` scope for people who make agreements.  People who are signing agreements really only need their identity provided by GitHub, so we  should only ask for the `(no scope)` "Public read-only-access" [GitHub OAuth scope](http://developer.github.com/v3/oauth/#scopes).

Related to, but different from, #17

**Comment by ferventcoder** [comment]
Can this be closed? https://github.com/clahub/clahub/pull/101#issuecomment-75479008

**Comment by genevec** [comment]
Closing! See #101
