### ISSUE TITLE
clahub.com doesn't provide SSL access

### ISSUE THREAD

**Issue by matsimon** [clahub/clahub#59]
I really like the idea and I'd like to contribute to a project that uses CLAhub to manage CLAs. I know there are some cost added by getting a SSL-certificate in order to enable HTTPS but I'm not so much in favour to use a service that requires me to pass personal data like a phone number yet doesn't provide at least transport security.

Instead of barking about missing tin foil hats, what would be needed to get SSL on clahub.com? :)

**Comment by mzagaja** [comment]
Closing this since it appears HTTPS is working.
