### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by jbenet** [clahub/clahub#68]
When authorizing, it seems to me that clahub asks for too many permissions. Can this be reduced? It certainly gave me pause to give clahub blanket write access to all my repos. Not that it would be misused by you, but bugs/compromized websites could seriously hurt projects.

I recommend moving to simple auth for author info, and then do per-repo authorization to add each CLA.

**Comment by ferventcoder** [comment]
This can be closed - see https://github.com/clahub/clahub/pull/101#issuecomment-75479008
