### ISSUE TITLE
CLAHub only checks for the latest commits in the webhook notification

### ISSUE THREAD

**Issue by esteve** [clahub/clahub#83]
If a pull request receives more commits after it's been opened, CLAHub will only check the latest commits in the webhook event.

For example, given user A (who hasn't signed the CLA for our repo) and user B (who has), if user A submits a pull request CLAHub will correctly mark the pull request as invalid. However, if user B pushes more commits to the same branch, CLAHub will mark the pull request as valid because it only knows about the latest commits.

This is a bit of a corner case, but it'd be good if CLAHub checked all commits up to the parent.

**Comment by mzagaja** [comment]
After further investigation it appears this was implemented in https://github.com/clahub/clahub/commit/1681b170e93d74d3d2e398f7e953645d46beeb2b so I'm going to close this.
