### ISSUE TITLE
I cannot delete a CLA

### ISSUE THREAD

**Issue by teleyinex** [clahub/clahub#95]
I've created an agreement, and every time I try to delete it, it fails. How can I delete it?

**Comment by hipersayanX** [comment]
Same here, when i want to delete an a agreement it give me the message:

>We're sorry, but something went wrong.

**Comment by mzagaja** [comment]
This issue does not reproduce in my dev instance so will put it on the docket for production.

**Comment by mzagaja** [comment]
Hi @teleyinex and @hipersayanX can you let me know what repo the agreement is for that you are trying to delete, and if it currently has a web hook listed in the repo "Settings --> Webhooks and Services" section? It may be related to this bug I identified from another test case: https://github.com/clahub/clahub/issues/122

**Comment by hipersayanX** [comment]
Hi, i have moved a personal repository to an organization, and then tried to delete the associated agreement and re-upload for the new repository, and then i had that error. I don't remember if i deleted the hooks before or after, but most probably after.

**Comment by mzagaja** [comment]
Ok if you give me the URL of the organization I can manually delete it from the DB and then you should be able to re-create the agreement.

**Comment by hipersayanX** [comment]
The original repository was [this](https://github.com/hipersayanX/webcamoid/) and the new repository is [this](https://github.com/webcamoid/webcamoid/)

**Comment by mzagaja** [comment]
Ok it is deleted you can try re-creating it now. Let me know if you have any further trouble.
